# Generated by Django 3.2.13 on 2022-06-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desciption',
            new_name='description',
        ),
    ]
