# register new user

## bad password

POST http://127.0.0.1:8000/users/register/
Content-Type: application/json

{
    "username": "testuser1",
    "password": "password",
    "password2": "password",
    "email": "test1@test.com"
}

###

## mismatch between password and password2

POST http://127.0.0.1:8000/users/register/
Content-Type: application/json

{
    "username": "testuser1",
    "password": "dkssud!!",
    "password2": "password",
    "email": "test1@test.com"
}

###

## good password

POST http://127.0.0.1:8000/users/register/
Content-Type: application/json

{
    "username": "testuser1",
    "password": "dkssud!!",
    "password2": "dkssud!!",
    "email": "test1@test.com"
}

###

## existing email

POST http://127.0.0.1:8000/users/register/
Content-Type: application/json

{
    "username": "testuser2",
    "password": "dkssud!!",
    "password2": "dkssud!!",
    "email": "test1@test.com"
}

###

## new testuser2

POST http://127.0.0.1:8000/users/register/
Content-Type: application/json

{
    "username": "testuser1",
    "password": "dkssud!!",
    "password2": "dkssud!!",
    "email": "test1@test.com"
}

###

## login with correct password

POST http://127.0.0.1:8000/users/login/
Content-Type: application/json

{
    "username": "testuser1",
    "password": "dkssud!!"
}

###

## login with wrong password

POST http://127.0.0.1:8000/users/login/
Content-Type: application/json

{
    "username": "testuser1",
    "password": "password"
}

###

## get profile

GET http://127.0.0.1:8000/users/profile/2/

###

PUT http://127.0.0.1:8000/users/profile/2/
Authorization: Token 23642b68689aa520dfc9ce5d810e044d4b94b822
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nickname"

ninaeros
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="position"

Backend
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="subjects"

Django, Flutter, React
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST http://127.0.0.1:8000/posts/
Authorization: Token 0a876f0b558437fb42c9a79c8d6ae4914182eb3a
Content-Type: multipart/form-data; boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Test POST
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="body"

Hello! This is body
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="category"

백엔드
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

HEAD http://127.0.0.1:8000/posts/

###

GET http://127.0.0.1:8000/like/1/
Authorization: Token 1563c960972fbc4459d185fb77b6862e6615a7fa

###

GET http://127.0.0.1:8000/posts/1/
Authorization: Token 1563c960972fbc4459d185fb77b6862e6615a7fa

###

POST http://127.0.0.1:8000/comments/
Authorization: Token 1563c960972fbc4459d185fb77b6862e6615a7fa
Content-Type: application/json

{
    "post": 1,
    "text": "좋은 글 잘 봤습니다."
}

###